[package]
name = "bevy_text_animation"
version = "0.6.0-rc.2"
edition = "2021"
repository = "https://github.com/funatsufumiya/bevy_text_animation"
description = "text animation library for Bevy"
license = "WTFPL OR 0BSD"
# autoexamples = false

[features]
default = []

[dev-dependencies]
# bevy = { version = "^0.18.0-rc.2", default-features = false, features = [
#     "bevy_asset",
#     "bevy_winit",
#     "bevy_window",
#     "bevy_render",
#     "bevy_text",
#     "bevy_ui",
#     "bevy_sprite",
#     "default_font"
# ] }

bevy = { version = "^0.18.0-rc.2" }

[dependencies]
bevy = { version = "^0.18.0-rc.2", default-features = false, features = [
    "bevy_text",
    "bevy_sprite",
    "bevy_ui",
] }
utf8_slice = "1.0.0"
